// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $dining from "./routes/dining.tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $me from "./routes/me.tsx";
import * as $tiffin from "./routes/tiffin.tsx";
import * as $Carousel from "./islands/Carousel.tsx";
import * as $counter_anchor from "./islands/counter-anchor.tsx";
import * as $triangles from "./islands/triangles.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/joke.ts": $api_joke,
    "./routes/dining.tsx": $dining,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/me.tsx": $me,
    "./routes/tiffin.tsx": $tiffin,
  },
  islands: {
    "./islands/Carousel.tsx": $Carousel,
    "./islands/counter-anchor.tsx": $counter_anchor,
    "./islands/triangles.tsx": $triangles,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
